/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AfrekenenRouteImport } from './routes/afrekenen'
import { Route as OverRouteImport } from './routes/over'
import { Route as VerlanglijstRouteImport } from './routes/verlanglijst'
import { Route as WinkelRouteImport } from './routes/winkel'
import { Route as BestellingIdRouteImport } from './routes/bestelling.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AfrekenenRoute = AfrekenenRouteImport.update({
  id: '/afrekenen',
  path: '/afrekenen',
  getParentRoute: () => rootRouteImport,
} as any)
const OverRoute = OverRouteImport.update({
  id: '/over',
  path: '/over',
  getParentRoute: () => rootRouteImport,
} as any)
const VerlanglijstRoute = VerlanglijstRouteImport.update({
  id: '/verlanglijst',
  path: '/verlanglijst',
  getParentRoute: () => rootRouteImport,
} as any)
const WinkelRoute = WinkelRouteImport.update({
  id: '/winkel',
  path: '/winkel',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellingIdRoute = BestellingIdRouteImport.update({
  id: '/bestelling/$id',
  path: '/bestelling/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afrekenen': typeof AfrekenenRoute
  '/over': typeof OverRoute
  '/verlanglijst': typeof VerlanglijstRoute
  '/winkel': typeof WinkelRoute
  '/bestelling/$id': typeof BestellingIdRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afrekenen': typeof AfrekenenRoute
  '/over': typeof OverRoute
  '/verlanglijst': typeof VerlanglijstRoute
  '/winkel': typeof WinkelRoute
  '/bestelling/$id': typeof BestellingIdRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afrekenen': typeof AfrekenenRoute
  '/over': typeof OverRoute
  '/verlanglijst': typeof VerlanglijstRoute
  '/winkel': typeof WinkelRoute
  '/bestelling/$id': typeof BestellingIdRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afrekenen'
    | '/over'
    | '/verlanglijst'
    | '/winkel'
    | '/bestelling/$id'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afrekenen'
    | '/over'
    | '/verlanglijst'
    | '/winkel'
    | '/bestelling/$id'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/afrekenen'
    | '/over'
    | '/verlanglijst'
    | '/winkel'
    | '/bestelling/$id'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfrekenenRoute: typeof AfrekenenRoute
  OverRoute: typeof OverRoute
  VerlanglijstRoute: typeof VerlanglijstRoute
  WinkelRoute: typeof WinkelRoute
  BestellingIdRoute: typeof BestellingIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afrekenen': {
      id: '/afrekenen'
      path: '/afrekenen'
      fullPath: '/afrekenen'
      preLoaderRoute: typeof AfrekenenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over': {
      id: '/over'
      path: '/over'
      fullPath: '/over'
      preLoaderRoute: typeof OverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verlanglijst': {
      id: '/verlanglijst'
      path: '/verlanglijst'
      fullPath: '/verlanglijst'
      preLoaderRoute: typeof VerlanglijstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winkel': {
      id: '/winkel'
      path: '/winkel'
      fullPath: '/winkel'
      preLoaderRoute: typeof WinkelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestelling/$id': {
      id: '/bestelling/$id'
      path: '/bestelling/$id'
      fullPath: '/bestelling/$id'
      preLoaderRoute: typeof BestellingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfrekenenRoute: AfrekenenRoute,
  OverRoute: OverRoute,
  VerlanglijstRoute: VerlanglijstRoute,
  WinkelRoute: WinkelRoute,
  BestellingIdRoute: BestellingIdRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
